### ISSUE TITLE
Demo app crashes on Android 5.1.1

### ISSUE THREAD

**Issue by dailystudio** [Orange-OpenSource/Datavenue-Android-SDK#1]
After I logged in with my account, when I click to create a new datasource, app crashed with following exception:

09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime: FATAL EXCEPTION: main
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime: Process: com.orange.datavenue, PID: 12678
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Dialog.findViewById(int)' on a null object reference
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at com.orange.datavenue.DatasourceFragment.onOptionsItemSelected(DatasourceFragment.java:297)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1897)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2046)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:541)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.view.View.performClick(View.java:4780)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19866)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
09-28 10:23:36.500 12678-12678/com.orange.datavenue E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by splendf** [comment]
The issue has been solved and an update has been pushed on git.
